//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _OnlineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string Source { get; set; }
        public string im1 { get; set; }
        public string im2 { get; set; }
        public string im3 { get; set; }
        public string im4 { get; set; }
        public string im5 { get; set; }
        public string Category { get; set; }
    }
}
