//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _OnlineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string bldNumb { get; set; }
        public string street { get; set; }
        public Nullable<int> zip { get; set; }
        public string country { get; set; }
        public string aptNumb { get; set; }
        public string Skype { get; set; }
        public string Viber { get; set; }
        public string sourceLink { get; set; }
        public string sLink { get; set; }
        public Nullable<int> sId { get; set; }
        public Nullable<int> sPrice { get; set; }
    }
}
